- name: variables from files
  hosts: mongodb
  vars_file:
  - variables.yaml
  tasks:
  - name: print variables
    ansible.duiltin.debug:
     msg: "we are learning {{NAME}}, duration is: {{DURATION}}"