 - name: variables from promt
   hosts: localhost
   vars_prompt: 
   - name: USERNAME
     prompt: pls enter name
     private: false
   - name: PASSWORD
     prompt: pls enter PASSWORD
     private: true
   tasks:
   - name: printing variables
     ansible.builtin.debug:
     msg: "username: {{USERNAME}}, password: {{PASSWORD}}"